"""widen precision for repeating-decimal cost rates

Revision ID: dd2f14f3c554
Revises: d954fd8ecc24
Create Date: 2026-08-30 13:35:59.303701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd2f14f3c554'
down_revision: Union[str, None] = 'd954fd8ecc24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cost_rate_settings', 'parchment_outturn_pct',
               existing_type=sa.NUMERIC(precision=6, scale=4),
               type_=sa.Numeric(precision=8, scale=6),
               existing_nullable=False)
    op.alter_column('cost_rate_settings', 'pulping_cost_per_kg_cherry',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=10, scale=6),
               existing_nullable=False)
    # ### end Alembic commands ###

    # Widening the column doesn't fix values already truncated at the old precision — the
    # seed row (id=1, if it exists and is still at its untouched default) is corrected here so
    # a database that was already seeded before this migration gets the exact rates too.
    op.execute(
        "UPDATE cost_rate_settings SET parchment_outturn_pct = 0.181818 "
        "WHERE id = 1 AND parchment_outturn_pct = 0.1818"
    )
    op.execute(
        "UPDATE cost_rate_settings SET pulping_cost_per_kg_cherry = 0.166667 "
        "WHERE id = 1 AND pulping_cost_per_kg_cherry = 0.1667"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cost_rate_settings', 'pulping_cost_per_kg_cherry',
               existing_type=sa.Numeric(precision=10, scale=6),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('cost_rate_settings', 'parchment_outturn_pct',
               existing_type=sa.Numeric(precision=8, scale=6),
               type_=sa.NUMERIC(precision=6, scale=4),
               existing_nullable=False)
    # ### end Alembic commands ###
